/*
 * Definitions.h
 *
 *  Created on: Dec 11, 2015
 *      Author: Bazyli
 */

#ifndef DEFINITIONS_H_
#define DEFINITIONS_H_


// SELF MESSAGE KINDS
#define SMSGKIND_INIT 0x00
#define SMSGKIND_SENDDATA 0x01
#define SMSGKIND_NETWORKDISCOVERY 0x02
#define SMSGKIND_SENDACK 0x03
#define SMSGKIND_DECTXACTIVE 0x04
#define SMSGKIND_TXCOMPLETE 0x05
#define SMSGKIND_MEDIUMFREE 0x06
#define SMSGKIND_TXATTEMPT 0x07
#define SMSGKIND_ACKTIMEOUT 0x08
#define SMSGKIND_LOGINTERVAL 0x09
#define SMSGKIND_TEST 0x0F

// MESSAGE KINDS
#define MSGKIND_DATA 0xF1
#define MSGKIND_HOPDISCOVER 0xF2
#define MSGKIND_ACK 0xF3
#define MSGKIND_TEST 0xFF

// EVENT MESSAGE KINDS
#define EVENTMSG_BATTERYEMPTY 0x0F01

// MESSAGE SIZES
#define MSGSIZE_DATA 1000       // bits
#define MSGSIZE_BIGDATA 40000   // bits
#define MSGSIZE_HOPDISCOVER 80  // bits
#define MSGSIZE_ACK 80          // bits

// MESSAGE TIMERS
#define MSGTIMER_MS_SENDACK     1       // in ms
#define MSGTIMER_TXATTEMPT      0.001   // in s

// RATES


// CONSTANTS
#define CONST_SPEEDOFLIGHT 300000000.0    // m/s units
#define CONST_SEC_PER_HOUR 3600.0
#define CONST_LARGE_INTVAL 32000

// PROTOCOLS
#define PROTOCOL_GREEDYGEO 0
#define PROTOCOL_GREEDYGRADIENT 1
#define PROTOCOL_ENERGYAWAREGRADIENT 2
#define PROTOCOL_ENERGYSMARTGRADIENT 3
#define PROTOCOL_QESMART 4
#define PROTOCOL_QBSMART 5
#define PROTOCOL_ENERGYAWAREHOPS 6
#define PROTOCOL_ENERGYSMARTHOPS 7


#endif /* DEFINITIONS_H_ */
